### ISSUE TITLE
Failed to minify code in react

### ISSUE THREAD

**Issue by shakyasaijal** [millicast/millicast-sdk#121]
**Version affected**
0.1.12

**Describe the bug**
Failed to minify the code of millicast.umd.js

**To Reproduce**
1. Delete node_modules
2. Re-install `yarn install`
3. Build react using react-scripts `yarn build`

**Screenshots**

![Screenshot from 2021-11-16 16-07-57](https://user-images.githubusercontent.com/35344219/141968162-c020ffdb-9987-4c20-97c5-f12ccf81a3c5.jpg)

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - React [v17.0.1]
 - react-scripts [v4.0.0]

**Comment by R-Delfino95** [comment]
I tried to reproduce the issue but I don't have any trouble when building a new React project.

Steps I did:
- Create new react project using `yarn create-react-app my-app`
- `yarn add @millicast/sdk@0.1.12`
- Import the Director module and console log the module inside the App.js
- `yarn build` -> working
- Reproduce your steps
  - `yarn build` -> working

Environment:
- OS: [Windows 10]
- React [v17.0.1]
- react-scripts [v4.0.0]
- yarn [v1.22.17]

I had a related problem in React when I mixed npm and yarn. I was using npm for the installation of dependencies and then using yarn to make new builds. Maybe it could be something related to that
