### ISSUE TITLE
Millicast View is not fluid on iphone safari, it has little jumps from time to time.

### ISSUE THREAD

**Issue by CastriOnlive** [millicast/millicast-sdk#127]
**Version affected**
0.1.16

**Describe the bug**
When using the SDK MillicastView in iphone 11 (safari 14), we experience brief jumps in the video, it does not happen using the millicast hosted player.

**To Reproduce**
1. Publish an Stream with Millicast Publish

```   
  const millicastPublish = new Publish(streamName, tokenGenerator);
  this.millicastPublish = millicastPublish;
  const broadcastOptions = {
      mediaStream: stream,
      simulcast: true,
      disableAudio: false,
      diableVideo: false,
      bandwidth: 0,
      codec: 'h264'
  }
  //Start broadcast
  return millicastPublish.connect(broadcastOptions)
```

2. Receive the Stream with Millicast View
  `//Millicast View 
    const tokenGenerator = () => Director.getSubscriber(streamName, accountId)
    const millicastView = new View(streamName, tokenGenerator, null, true);`

3. Use an iphone with safari 14.0 to test the millicast view.
4. **_OPTIONAL:_** Open the millicast hosted player and compare the streams, the hosted player is more fluid.

**Expected behavior**
The video should be fluid and not have jumps when using iphone (safari 14)

**Screenshots**
Not possible to provide screenshot

**Environment (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version 14

**Additional context**
**NOTE:**
This issue does not happen with android chrome, neither in the millicast hosted player with any other device.

**Comment by murillo128** [comment]
@R-Delfino95 can you try to reproduce it? is there any timer running on the sdk?

**Comment by R-Delfino95** [comment]
> @R-Delfino95 can you try to reproduce it? is there any timer running on the sdk?

The SDK run timers when tries to reconnect and when you init the stats (by default is turned off).
I have an Iphone 5s that we could use to replicate the issue.

**Comment by CastriOnlive** [comment]
> 

Hi @R-Delfino95 I forgot to mention that we call init stats.

**Comment by murillo128** [comment]
@CastriOnlive could you check if the jumps also happen if you don't init the stats?

**Comment by CastriOnlive** [comment]
I tested without using init stats and it works fine without jumps

**Comment by R-Delfino95** [comment]
Freezes can happen in some browsers when [running statistics](https://millicast.github.io/millicast-sdk/PeerConnection.html#initStats), use it when necessary and if it is already started you can use the [stopStats](https://millicast.github.io/millicast-sdk/PeerConnection.html#stopStats) method.

Thank you for reporting it!

**Comment by CastriOnlive** [comment]
@R-Delfino95  Hello again, we really need the initStats for knowing if the client has packet loss and reporting, is it possible to move the initStats to a Worker and it improves that way?
