### ISSUE TITLE
Simulcast Cloud Recordings: Audio Sync and Video Flaws

### ISSUE THREAD

**Issue by EmersonGGS** [millicast/millicast-sdk#158]
**Version affected**
0.1.26

**Describe the bug**
When a client is publishing with simulcast on, the cloud file that is recorded has video flaws and audio out of sync.

Codecs: VP8, Opus

**To Reproduce**
1. Start pulishing with simulcast ON and recording ON
2. Record for 2 minutes with motion and audio
3. Stop publishing
4. Review cloud video recording

**Expected behavior**
Cloud recording should be smooth and audio should remain in-sync.

**Screenshots**
Example video can be provided.

**Environment**
 - OS: Windows 11
 - Browser: Chrome 
 - Version 100.0.4896.127

**Comment by nico-ramos** [comment]
Closing this issue, this should be handled server-side and reported to https://support.dolby.io/hc/en-au
