### ISSUE TITLE
Publisher Demo - Mobile Chrome - Does not recognize camera/mic

### ISSUE THREAD

**Issue by matthewclickbid** [millicast/millicast-sdk#180]
**Version affected**
Current version

**Describe the bug**
When using the Millicast Publisher Demo (publisher.js) it will not give you any options for camera/mic. It throws an error: 

> Could not get Media:  DOMException: Could not start video source
> DOMException: Could not start video source

Removing constraint parameters resolves the issue. Lines 206 - 211 were removed and the issue was resolved.

**Comment by nico-ramos** [comment]
Thanks, already fixed in main branch.
