### ISSUE TITLE
Publisher Demo - Change audio/video/mute during broadcast breaks controls

### ISSUE THREAD

**Issue by matthewclickbid** [millicast/millicast-sdk#181]
**Version affected**
Current version

**Describe the bug**
Switching audio or video while broadcasting will result in losing the source of the non-affected audio/video track. In addition, muting audio does not always mute audio (video either). Seems inconsistent. If you toggle mute on and then off, it regains the proper status.

**To Reproduce**
Start a broadcast.
Start a viewer on another device.
Switch camera on broadcaster.
Notice that audio is now muted on viewer.
Switch audio on broadcater.
Notice that audio works but video goes blank.
Refresh and re-start broadcast.
Notice that both audio and video work again.

**Comment by olbapbetan** [comment]
Hi matthewclickbid,

Thank you for letting us know that you are facing issues with the [Publisher Demo](https://github.com/millicast/millicast-sdk/tree/main/packages/millicast-publisher-demo).

I have taken a look at it but, unfourtenately, I have not been able to reproduce the problems you have mentioned.

I followed the steps you provided:
1. Started a broadcast, which I tapped to listen to the audio.
2. Started a web viewer from viewer.millicast.com, in another window.
3. Switched camera on broadcast, but the viewer remains unmuted.
4. Switched audio on broadcast, but the video remains playing as before.

Are you sure that you have followed these especific steps?

In case of a positive answer, could you provide more information of the system that you are usig it like OS and browser?

From my part, I have tested it in Windows 11, in Chrome, Firefox and Edge, and it works as expected in all of them.

Kind regards,
Pablo.

**Comment by nico-ramos** [comment]
We were not able to reproduce this
