### ISSUE TITLE
Multi-stream controls and UI not showing on video

### ISSUE THREAD

**Issue by ademola-raimi** [millicast/millicast-sdk#187]
I am working on multi-stream based on this [doc](https://docs.dolby.io/streaming-apis/docs/audio-multiplexing). I was able to set up two different feeds on the browser with test-1 and test-2. I can also view it on the browser using the hosted [path](https://viewer.millicast.com?streamId=mYZ8AK/l3xbx282), which looks like the image below.

But trying to reproduce the same programmatically using the millicastSDK; only shows the pinnedSourceId stream without the controls and the UI. I have also attached an image of my local environment.

![image (1)](https://user-images.githubusercontent.com/14159420/194422258-b997f91e-5bc0-46ff-be69-e3867cf2abc0.png)
<img width="1440" alt="Screenshot 2022-10-06 at 22 29 33" src="https://user-images.githubusercontent.com/14159420/194422288-68410ec5-8384-459f-b7a8-f60392cf53ff.png">

Here is basically the code I am using:

```
const tokenGenerator = () =>
      Director.getSubscriber({
        streamName: streamName,
        subscriberToken: viewerToken
      });

    if (!video.current) {
      return;
    }

    //Create viewer
    const millicastView = new View(streamId, tokenGenerator, video.current);
    millicastView.connect({
      pinnedSourceId,
      dtx: true,
    }).catch(e => console.log('error: ', e))

```

where streamId = "mYZ8AK/l3xbx282";
pinnedSourceId = "test-1" //the sourceId of the first broadcast

Any help will be greatly appreciated. Thanks.

**Comment by nico-ramos** [comment]
Hi! seeing your comment made us realize that the documentation regarding multi-source streaming is not clear so we'll be fixing that, thanks!.

**About your question:**
First, the controls and UI is up to **you** to implement, the SDK only provides an easier way to interact with the streaming service so you can implement your customized app.

Whats happening to you is that you only insert the main track into the video, if you want to see multiple sources you have to listen to the `active` `broadcastEvent` and then project that track into a new `<video>` tag. For each source you'll need to create a new `<video>` tag to insert the `MediaStream` in it. To do this you'll have to use a few other methods. Bellow a small guide to accomplish multi-source viewer like our hosted web app.

**1. First create a new `View` instance:**

```javascript
const tokenGenerator = () => Director.getSubscriber(YOUR_STREAM_NAME, YOUR_ACCOUNTID)
const millicastView = new View(YOUR_STREAM_NAME, tokenGenerator)
```
**2. Add Listener to add the main MediaStream into the video tag (optional since i dont provide the initial video tag to the View instance creation):**
Note:  I have a `<video>` tag with an id of `mainVideo` rendered, this will be the main screen.
```javascript
//Listen for the track event
millicastView.on('track', (event) => {
     if (event.streams.length) {
        document.getElementById('mainVideo').srcObject = event.streams[0]
     }
})
```

**3. Listen for the [broadcastEvents](https://millicast.github.io/millicast-sdk/Signaling.html#event:broadcastEvent) and update the UI based on which event comes, (I only implemented the active case for simplicity)**

```javascript
//Listen for the broadcastEvent based on which event arrives
millicastView.on('broadcastEvent', async (event) => {
      const {name, data} = event
      if( name === 'active' ) {
            if(data.sourceId) { // Is a side source, if it's the main source then sourceId is null
              const mediaStream = new MediaStream()
              const videoTransceiver = await millicastView.addRemoteTrack("video", [mediaStream])
              const audioTransceiver = await millicastView.addRemoteTrack("video", [mediaStream])
              //Create a new Video Element
              const vid = document.createElement('video');
              vid.autoplay = true;
              //your implementation:
              renderVideoInUI(vid)
              //Assign the mediaStream instance to a new video tag.
              vid.srcObject = mediaStream
              //Project the new source into the new video through the transceivers
              await millicastView.project(data.sourceId,[{
                trackId: "video",
                mediaId: videoTransceiver.mid,
                media: "video"
              },
              {
                trackId: "audio",
                mediaId: audioTransceiver.mid,
                media: "audio"
              },])
            }
      }
})
```
**Important Note: I only implemented the case of name === 'active', you should also implement the cases of name === 'inactive' which is fired when a source is stopped, you'll have to remove the video tag that uses that source and optionally unproject the soruce using [unproject](https://millicast.github.io/millicast-sdk/View.html#unproject) method. There's another event 'stopped' which is when the stream is stopped and should be handled**

**4. Finally we call the connect method with the necessary options:**

```javascript
try {
      await millicastView.connect({
            events: ['active', 'inactive', 'viewercount']
        })
} catch (error) {
      console.log(error)
      millicastView.reconnect()
}
```

Hopefully this was clear enough and helped to resolve your issue.

**Comment by ademola-raimi** [comment]
Hello Nicolas,

Thank you so much for this detailed explanation.

This was very helpful, and I have implemented it following the steps you
highlighted in your email.

Once again, thank you,

Kind regards,
Ademola.

**Comment by ademola-raimi** [comment]
It worked; thank you for the help. I do have one follow-up question regarding the solution. I did everything based on your instructions. I noticed a bug where the side source, after playing for a few minutes, remains frozen until I refresh the page. The live multisource works perfectly fine without freezing. I was wondering if you know why that is. My broadcast code looks like this:

  ```
useEffect(() => {
    if (!milliView) {
      return;
    }
    milliView.on('broadcastEvent', async (event) => {
      const { name, data } = event;
      switch (name) {
        case 'active':
          if (data.sourceId) {
            if (data.sourceId in sideSources) {
              milliView.unproject([sideSources[data.sourceId].videoTransceiver, sideSources[data.sourceId].audioTransceiver]);
            }
            const mediaStream = new MediaStream();
            const videoTransceiver = await milliView.addRemoteTrack("video", [mediaStream])
            const audioTransceiver = await milliView.addRemoteTrack("audio", [mediaStream])
            const sideSource = {
              mediaStream,
              videoTransceiver,
              audioTransceiver
            }
            setSideSources(prevState => ({
              ...prevState,
              [data.sourceId]: sideSource
            }));
            await milliView.project(data.sourceId,[{
              trackId: "video",
              mediaId: videoTransceiver.mid,
              media: "video"
            },
            {
              trackId: "audio",
              mediaId: audioTransceiver.mid,
              media: "audio"
            }])
          }
          break;
        case 'inactive':
          if (data.sourceId) {
            const sideSource = sideSources[data.sourceId];
            milliView.unproject([sideSource.videoTransceiver, sideSource.audioTransceiver]);
            setSideSources(current => {
              const copy = {...current};
              delete copy[data.sourceId];

              return copy;
            });
            if (Object.keys(sideSources).length > 0 && pinnedSourceId === data.sourceId) {
              const nextSideSource = sideSources[Object.keys(sideSources)[0]];
              projectSourceAsMain(Object.keys(sideSources)[0], nextSideSource);
            }
          }
          break;
        case 'viewercount':
          if (data.viewercount) {
            setViewerCount(data.viewercount)
          }
          break;
        default:
          break;
      }
    });
  }, [milliView, Object.keys(sideSources).length, pinnedSourceId]);
```

I'll be looking forward to hearing from you.

**Comment by nico-ramos** [comment]
The freezing issue might be related to the built-in bandwidth limitation with multisource (at the end of this document: https://docs.dolby.io/streaming-apis/docs/source-and-layer-selection). Basically you should publish your side sources with a limited bandwidth so the sum of all of them is less than 4mbps (For example try publishing each source with 150 bitrate). Another way is enabling simulcast but this only works in Chrome at the moment.

Also when this happens, is it also happening on our hosted viewer app? or just yours?

I didn't check your code yet, tell me if this fixes your issue and i'll investigate

**Comment by ademola-raimi** [comment]
It doesn't happen on the hosted viewer; it only happens in mine

**Comment by ademola-raimi** [comment]
I have also noticed that when I pass in a sourceId while connecting, that stream doesn't freeze. Apparently, it happens to only those streams I automatically project.

`millicastView.connect({ pinnedSourceId, events: ['active', 'inactive', 'viewercount'] })`

**Comment by ademola-raimi** [comment]
Hi, I think you were right; it's a bandwidth issue. I just took both videos down to 1000 bitrate and 720 and it works extremely smoothly! Now can you show me an example of how to limit the bandwidth in the application, so it doesn't go more than 4mbps? I  believe it should just be as simple as adding layer when projecting as seen in the code below:

```
viewer.project("mysource",[
    {
        trackId: "video0",
        mediaId: videoTransceiver.mid
        layer: 
        {
            encodingId : "L",
            temporalLayerId : 1
        }
    }
]);
```

But I don't know what encodingId and temporalLayerId mean. Can you explain them to me please?

**Comment by nico-ramos** [comment]
Hi, the bitrate can only be limited on the publisher side. From our hosted publisher (inside the dolby dashboard) can be done by changing the `Bandwidth` option, and from the sdk can be done in the by using the `bandwidth` option inside the `connect` method of the `Publish` class (https://millicast.github.io/millicast-sdk/Publish.html#connect) (or using the `publish.webRTCPeer.updateBitrate` function https://millicast.github.io/millicast-sdk/PeerConnection.html#updateBitrate).

If you want to send multiples qualities you can use `simulcast` option in the publish side (only available in Chrome and not with every codec). This can be handled in the viewer side by subscribing to the `layers` broadcastEvent, and then you'll have to include it in your switch-case of your `broadcastEvent` handler (`case 'layers'`). The info of the layer event looks like this: 

![image](https://user-images.githubusercontent.com/86117268/196507265-b3f14659-7d28-4091-b729-403d6a126c93.png)

With this information you can make a quality selector for example, and send the encodingId in the `project` method or with the [select method](https://millicast.github.io/millicast-sdk/View.html#select). Layer info:  https://millicast.github.io/millicast-sdk/global.html#LayerInfo

**Comment by CastriOnlive** [comment]
I am publishing with 720p and 1000kbps bandwidth and it gets stuck so much

**Comment by CastriOnlive** [comment]
@nico-ramos I have noticed that it freezes to me when the time passes or if refreshing and the bandwidth of each stream is limited to only 1000 kbps and the signal 540p 30fps, we have not been able to use yet the multisource because of the freezing thing.

**Comment by nico-ramos** [comment]
Hi, this issue looks like is server-side and should be reported via https://support.dolby.io/hc/en-au. I'm also experiencing some freezing issues. Anyways i already notified the team to see if they can find a solution.
I'll keep this issue open

**Comment by dcoffey3296** [comment]
Hello, we have released an update to our media server to address the freezing issues.  Can you retry and see if you experience the same issues?  

We also released a new guide that identifies limitations when doing multi-source/multi-view
https://docs.dolby.io/streaming-apis/docs/create-multi-view-web-app#limitations

let us know how your testing goes, thank you!
