### ISSUE TITLE
Provide .d.ts file for sdk types

### ISSUE THREAD

**Issue by brianathere** [millicast/millicast-sdk#193]
To aid development in typescript code bases, please provide a millicast_Sdk.d.ts file.

We're building one locally to make it easier to integrate the millicast-sdk into our client. I've provided a PR to make a few small corrections to the JS Doc.

**Comment by DannyBiezen** [comment]
I'm currently running `npx dts-bundle-generator -o /millicast.d.ts ./src/index.js` to generate a typescript declaration from the source code. This somewhat works but there are a couple of issues with this.
* I need to keep regenerating this file whenever a new version gets released to make sure my typings are correct

* The generated typings are incomplete - which means I have to manually patch them.
In some cases I can fix it myself, e.g. I need to add typings for the `EventEmitter` so `view.on` exists.
```
export class EventEmitter {
    static listenerCount(emitter: EventEmitter, type: string | number): number;
    static defaultMaxListeners: number;

    eventNames(): Array<string | number>;
    setMaxListeners(n: number): this;
    getMaxListeners(): number;
    emit(type: string | number, ...args: any[]): boolean;
    addListener(type: string | number, listener: Listener): this;
    on(type: string | number, listener: Listener): this;
    once(type: string | number, listener: Listener): this;
    prependListener(type: string | number, listener: Listener): this;
    prependOnceListener(type: string | number, listener: Listener): this;
    removeListener(type: string | number, listener: Listener): this;
    off(type: string | number, listener: Listener): this;
    removeAllListeners(type?: string | number): this;
    listeners(type: string | number): Listener[];
    listenerCount(type: string | number): number;
    rawListeners(type: string | number): Listener[];
  }
```

In some cases I'm not familiar enough with this library to know what type I need to use:
![image](https://user-images.githubusercontent.com/94181463/205285476-e8a5e8de-00d5-4aad-b6e0-479726b2d3ed.png)


This would be a great addition to the library!

**Comment by fcancela** [comment]
Type definitions have been added in the release [v0.1.36](https://github.com/millicast/millicast-sdk/releases/tag/v0.1.36)
