### ISSUE TITLE
Unable to stop reconnect

### ISSUE THREAD

**Issue by annidai** [millicast/millicast-sdk#194]
**Version affected**
The version I'm using is `0.1.34`

**Describe the bug**
After I set reconnect when the connection failed, I'm unable to stop the reconnection.

Here is the code snip for connect:
```
try {
    await millicastView.connect({
      events: ['active', 'stop', 'inactive', 'layers', 'viewercount'],
      absCaptureTime: true,
    });
  } catch (e) {
    millicastView.reconnect();
  }
```
When I try to cleanup the connection when the user chooses to stop connection by:

```
await millicastView.stop();
millicastView = null;
```

The console still keeps having errors:
```
millicast.umd.js:1          POST https://director.millicast.com/api/director/subscribe 400
```
<img width="687" alt="Screen Shot 2022-10-19 at 10 24 29 PM" src="https://user-images.githubusercontent.com/102047388/196841396-3bf61392-7589-42d9-a4a5-09ca4e0d0a11.png">

I see that in the `flutter-sdk`, it provides a way to stop reconnection. See [code](https://github.com/millicast/flutter-sdk/blob/286c3a89cc046e5c41e9156ccfec0b93434c8ca1/lib/src/utils/base_web_rtc.dart#L116)

Can we add something similar as well?

**Comment by nico-ramos** [comment]
Thanks for reporting the issue, we'll work on it

**Comment by chogarcia** [comment]
still does not work for me
