### ISSUE TITLE
Publisher's `inactive` and `active` events are triggered by viewer

### ISSUE THREAD

**Issue by annidai** [millicast/millicast-sdk#211]
**Version affected**
We are using version 0.1.36.

**Describe the bug**
The publisher is subscribing to broadcast events `inactive` and `active`.
However, these are not triggered when the publisher starts/ends streaming.
Instead, when a viewer starts viewing, the `active` event was triggered, and if a viewer stops viewing, the `inactive` event was triggered.

**To Reproduce**
1. Setup a publisher as follow, and start streaming
```
const publisher = new Publish(streamName, tokenGenerator); 
publisher.on('broadcastEvent', (event) => {
      console.log(event);
    });
await publisher.connect({
      bandwidth: 2000,
      events: [
        'active',
        'inactive'
      ],
      simulcast: true,
      mediaStream: mediaStream,
    });
```
2. Connect to the streaming as a viewer, then in the console log of the publisher, an `active` event will be triggered and logged
3. Close the viewer page, then in the console log of the publisher, an `inactive` event will be triggered and logged

**Expected behavior**
Based on the document, I assume the `active` and `inactive` events should be triggered by the publisher's connection activity, not the viewer's.

**Screenshots**
Please see the video:
If it's too blurry, download the file to have a better view.
https://drive.google.com/file/d/1UBwnbYYF6k9sHJuYLGGWbfxNErkKmgHq/view?usp=sharing

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: chrome and safari
 - Version: latest

**Comment by murillo128** [comment]
That's the intended behavior.

The `active`, `inactive` triggers on the publisher when there is viewer watching the stream, and on the viewer when there is a publisher publishing the stream. Is there anyway in the documentation that says the opposite or is not clear enough?

**Comment by annidai** [comment]
The documentation states as follow:

Active - Fires when the live stream is, or has started broadcasting.

Inactive - Fires when the stream has stopped broadcasting, but is still available.

> That's the intended behavior.
> 
> The `active`, `inactive` triggers on the publisher when there is viewer watching the stream, and on the viewer when there is a publisher publishing the stream. Is there anyway in the documentation that says the opposite or is not clear enough?

**Comment by CastriOnlive** [comment]
Hello have are also experiencing this issue, I know it is the intended behaviour, but we need to know the exact moment a stream gets active for the first time, since millicast has a timeout that could wait even 32 seconds for a stream, and our application is realtime so we cannot afford waiting for so long, is it possible to add a feature to know when a stream is active for the first time in realtime.
Note: we can do this on our side with websockets or a realtime service but we have clients that use obs to stream to millicast and in this case we need to know the exact moment the stream gets published for the first time.

**Comment by FabienLavocat** [comment]
@CastriOnlive apologies for the late response 😞 
The way I do it if I do not want to wait for that long is to not set `autoReconnect` and handle the reconnection on my own, that way instead of increasing the wait time, you can set a fix time of a couple of seconds.
