### ISSUE TITLE
View.connect(streamName) streamName is now deprecated 

### ISSUE THREAD

**Issue by sneaky-peeky** [millicast/millicast-sdk#400]
What should we use instead of streamName?

**Comment by sneaky-peeky** [comment]
okay, it is not breaking anything but typescript is saying View is deprecated. But yeah in the end it works, so no problems. Thank you for the answer
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/5e77cac0-5989-40e5-b17f-e97789710935">

**Comment by FabienLavocat** [comment]
Yes, we fixed that warning in the recent [0.2.0](https://github.com/millicast/millicast-sdk/releases/tag/v0.2.0) release.
