### ISSUE TITLE
can I set what video quality I want to receive as a viewer? 

### ISSUE THREAD

**Issue by sneaky-peeky** [millicast/millicast-sdk#401]
So when I am creating View instance and then connection to the stream is there a way I can set video quality to get? I am checking ViewConnectOptions but I don't see anything about video quality in there

**Comment by FabienLavocat** [comment]
What you can do is subscribe to the `layers` message in `broadcastEvent` (see https://docs.dolby.io/streaming-apis/docs/web#broadcast-events) and then you can select the layer you want to receive (see https://millicast.github.io/millicast-sdk/View.html#select).

**Comment by sneaky-peeky** [comment]
@FabienLavocat  awesome, don't understand how I wasn't able to find answer myself. Thanks a lot, you were very helpful.

**Comment by FabienLavocat** [comment]
It's good feedback, I'll work with our team to make our docs easier to understand regarding this topic.
