### ISSUE TITLE
Identify viewers

### ISSUE THREAD

**Issue by bigbean17** [millicast/millicast-sdk#422]
Hi,

We are trying to make an admin page for our broadcasts, so admins could see information such as all the viewers' name and viewing duration. Currently we are maintaining our own viewer list, is it possible to do with millicast-sdk? 

Thank you!

**Comment by Santiago-Souto** [comment]
Hey @bigbean17 ! Thanks for your question. The millicast-sdk does not have any feature regarding viewers' information, either from the Publisher side nor from the Viewer side.
