### ISSUE TITLE
TypeScript Errors: TS1170 and TS2304 when using milicast sdk 0.2.1

### ISSUE THREAD

**Issue by vasylynkar** [millicast/millicast-sdk#434]
https://github.com/millicast/millicast-sdk/blob/8072bf86823439f83e92fcb4ee601c0a043d2a04/packages/millicast-sdk/src/types/index.d.ts#L522

I'm encountering TypeScript errors when using the milicast sdk 0.2.1 package in my project. The errors are as follows:

TS1170: A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.

TS2304: Cannot find name `qualityLimitationDurations`.

These errors occur in the following scenario:

Steps to Reproduce:
1. Install the package using npm or yarn.
2. Import the relevant module(s) from the package.
3. Attempt to use the module(s) in a TypeScript file.
4. Run tsc (TypeScript compiler) to compile the TypeScript code.

Expected Behavior:
The code should compile without any TypeScript errors.

Actual Behavior:
The TypeScript compiler throws the following errors:

```
TS1170: A computed property name in a type literal must refer to an expression whose type is a literal type or a 'unique symbol' type.
TS2304: Cannot find name 'qualityLimitationDurations'.
```

Possible Solution:
It seems like `qualityLimitationDurations `is not defined or imported correctly within the package, and there is a problem with the computed property name being used in a type literal. A possible solution could involve ensuring all variables are properly defined and that computed properties use only literal types or unique symbols.

**Comment by FabienLavocat** [comment]
Thank you for reporting this error. We are working on switching the SDK into pure TypeScript instead of JavaScript with some TypeScript definitions, which should fix this problem. In the meantime, are you able to use the [skipLibCheck](https://www.typescriptlang.org/tsconfig/#skipLibCheck) flag to remove this error when you compile your project?

**Comment by vasylynkar** [comment]
Thanks for the fast answer!
