### ISSUE TITLE
After upgrading from v0.2.1 to v0.3.0 the browser hangs while page load

### ISSUE THREAD

**Issue by vpmedia** [millicast/millicast-sdk#469]
**Version affected**
v0.3.0

**Describe the bug**
After upgrading from v0.2.1 to v0.3.0 the browser hangs while page load. The browser just keeps showing progress of page load, no trace of console log errors. Our application with the embedded SDK does not complete the page load at all.
Maybe something is broken with the release.
We are using Vite as bundler.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Safari, Chrome

**Comment by FabienLavocat** [comment]
Thanks for reporting this problem, I'm also able to reproduce it, however, for some reason, running the command `vite preview` works while `vite` is stuck loading forever. We're looking into this problem.

**Comment by FabienLavocat** [comment]
@vpmedia we pinpoint the source of the problem (related to a dependency) we're working on testing a new build and will publish a new version of the SDK (patch 0.3.1) asap.

**Comment by FabienLavocat** [comment]
@vpmedia we've released the version [0.3.1](https://github.com/millicast/millicast-sdk/releases/tag/v0.3.1) that fixes the issue with `vite` bundler. Let us know if you still face the issue with your app.
