### ISSUE TITLE
View class project method undocumented behaviour

### ISSUE THREAD

**Issue by snoh666** [millicast/millicast-sdk#471]
Within millicastSdk documenation method `project` (in Class `View`) does not accept sourceId to be anything than `string`, but when I pass  value with  type `any` (`value = undefined | null`). It works fine and selects Main source stream

```
await millicastView.project(sourceId, [...
```

Is that expected?

**Comment by FabienLavocat** [comment]
@snoh666 this is an expected behavior, as the SDK does not check the content of the variable that you pass. It is directly sent as a message to the web socket ([see](https://github.com/millicast/millicast-sdk/blob/main/packages/millicast-sdk/src/View.js#L180)).
