### ISSUE TITLE
Allow the publisher to specify the peerconnection configuration on connect

### ISSUE THREAD

**Issue by murillo128** [millicast/millicast-sdk#72]
We should allow to pass the peerconnection configuration on the connect method:

https://github.com/millicast/millicast-sdk/blob/main/packages/millicast-sdk/src/Publish.js#L108

We should mix both user provided configuration and the configuration provided (for example to use the iceservers provided by the http rest api)

**Comment by R-Delfino95** [comment]
Great! Should we pass the PeerConnection configuration for View module too?

**Comment by murillo128** [comment]
yes please
