### ISSUE TITLE
Improve startup times

### ISSUE THREAD

**Issue by murillo128** [millicast/millicast-sdk#85]
Currently we are doing all PC and ws sequentially which leads to high startup times.

We have to paralelize as much as possible:
- get token
- in paralell
     - connect the ws (i n the future we will return turn servers in token, so we can't start the ws token before the ws connection)
     - get local support and modify it

- when local sdp is retrieved and ws is connected send view command
- when local sdp is retrieved set it on PC
- when local sdp is set and remote answer is retrieved, set remote description

**Comment by murillo128** [comment]
ptal

**Comment by R-Delfino95** [comment]
Hi @murillo128, looks good to me. We are going to make that changes
